import { Suspense } from "react";
import { useTranslation } from "react-i18next";
import { QueryClientProvider } from "@tanstack/react-query";

import { queryClient } from "@shared/api";
import { RankingsPage } from "@features/rankings";
import "@shared/i18n";
import { LanguageSwitcher } from "@shared/i18n/LanguageSwitcher";

// Chunk 4 App shell: now hosts the rewritten rankings page directly.
// The router skeleton in chunk 5 turns this into the rankings route
// proper and pushes language switcher into a global header.
function AppInner() {
  const { t } = useTranslation("common");

  return (
    <main className="min-h-screen bg-surface text-fg">
      <header className="mx-auto flex max-w-5xl items-center justify-between px-6 py-4">
        <div>
          <p className="text-xs uppercase tracking-wider text-fg-subtle">
            {t("brand")}
          </p>
          <p className="text-sm text-fg-muted">{t("tagline")}</p>
        </div>
        <LanguageSwitcher />
      </header>

      <div className="mx-auto max-w-5xl px-6 pb-12">
        <RankingsPage />
      </div>
    </main>
  );
}

export function App() {
  // QueryClientProvider wraps the tree so feature hooks generated by
  // graphql-codegen (useVersionsQuery, useChampionRankingsQuery, …)
  // have a client to plug into. The same instance is reused across
  // the whole app — see queryClient.ts for tuning rationale.
  //
  // i18n init is synchronous (resources are bundled), but Suspense
  // here costs nothing and means the Trans/useTranslation hooks behave
  // correctly when chunk 4 swaps to lazy-loaded namespaces.
  return (
    <QueryClientProvider client={queryClient}>
      <Suspense fallback={<div className="p-8 text-fg-muted">Loading…</div>}>
        <AppInner />
      </Suspense>
    </QueryClientProvider>
  );
}
