package resolver

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.91

import (
	"context"
	"fmt"
)

// Versions is the resolver for the versions field.
func (r *queryResolver) Versions(ctx context.Context) ([]string, error) {
	out, err := r.Catalog.ListVersionsWithData(ctx)
	if err != nil {
		return nil, fmt.Errorf("versions: %w", err)
	}
	return out, nil
}

// Regions is the resolver for the regions field.
func (r *queryResolver) Regions(ctx context.Context) ([]string, error) {
	out, err := r.Catalog.ListRegionsWithData(ctx)
	if err != nil {
		return nil, fmt.Errorf("regions: %w", err)
	}
	return out, nil
}
