package resolver

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.91

import (
	"context"

	gqlgenerated "github.com/crafff/gogg/apps/api/internal/transport/graphql/generated"
)

// Ok is the resolver for the _ok field.
func (r *queryResolver) Ok(_ context.Context) (bool, error) {
	return true, nil
}

// Query returns gqlgenerated.QueryResolver implementation.
func (r *Resolver) Query() gqlgenerated.QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
