// Package resolver hosts the gqlgen resolvers for the gogg-api GraphQL
// surface. Each .resolvers.go file in this package is regenerated by
// gqlgen against the schema; resolver.go (this file) is hand-edited
// and carries the dependency wiring.
//
// Resolvers do only orchestration: translate gqlgen input/output types
// to/from the service layer, call exactly one service method, and let
// gqlgen format errors. Business logic stays in the service packages
// per the architecture rule in CLAUDE.md.
package resolver

import (
	"context"

	"github.com/crafff/gogg/apps/api/internal/service/rankings"
)

// CatalogService is the narrow surface the catalog resolvers need.
// Mirrors v1.CatalogService but defined here so the GraphQL transport
// has no compile-time dependency on the REST transport.
type CatalogService interface {
	ListVersionsWithData(ctx context.Context) ([]string, error)
	ListRegionsWithData(ctx context.Context) ([]string, error)
}

// RankingsService is the narrow surface the rankings resolver needs.
// Same shape as v1.RankingsService — kept duplicated here to preserve
// the consumer-defined-interface convention across transports.
type RankingsService interface {
	GetOverall(ctx context.Context, f rankings.Filter) (rankings.Result, error)
	GetByPosition(ctx context.Context, f rankings.Filter) (rankings.Result, error)
}

// Resolver is the root dependency container the executable schema is
// constructed with. main.go builds one and hands it to
// gqlgenerated.NewExecutableSchema.
type Resolver struct {
	Catalog  CatalogService
	Rankings RankingsService
}
