package resolver

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.91

import (
	"context"
	"fmt"
	"time"

	"github.com/crafff/gogg/apps/api/internal/service/tft"
	"github.com/crafff/gogg/apps/api/internal/transport/graphql/domainerr"
	gqlgenerated "github.com/crafff/gogg/apps/api/internal/transport/graphql/generated"
	"github.com/crafff/gogg/apps/api/internal/transport/middleware"
)

// RefreshTFTPlayer is the resolver for the refreshTFTPlayer field.
func (r *mutationResolver) RefreshTFTPlayer(ctx context.Context, identity gqlgenerated.TFTIdentityInput) (*gqlgenerated.TFTRefreshResult, error) {
	result, err := r.TFT.Refresh(ctx, tft.Identity{Platform: identity.Platform, GameName: identity.GameName, TagLine: identity.TagLine}, middleware.ClientIPFromContext(ctx))
	if err != nil {
		return nil, mapTFTError(err)
	}
	return &gqlgenerated.TFTRefreshResult{Fresh: result.Fresh, Reused: result.Reused, Job: mapTFTLookupJob(result.Job)}, nil
}

// TftAnalysisCatalog is the resolver for the tftAnalysisCatalog field.
func (r *queryResolver) TftAnalysisCatalog(ctx context.Context) ([]*gqlgenerated.TFTAnalysisCatalogEntry, error) {
	rows, err := r.TFT.Catalog(ctx)
	if err != nil {
		return nil, fmt.Errorf("TFT analysis catalog: %w", err)
	}
	out := make([]*gqlgenerated.TFTAnalysisCatalogEntry, 0, len(rows))
	for _, row := range rows {
		out = append(out, &gqlgenerated.TFTAnalysisCatalogEntry{Platform: row.Platform, Patch: row.Patch, SetNumber: row.SetNumber, QueueID: row.QueueID, Cohort: gqlgenerated.TFTCohort(row.Cohort), Window: gqlgenerated.TFTWindow(row.Window), PublishedAt: row.PublishedAt.UTC().Format(time.RFC3339), SourceMatches: int(row.SourceMatches), SourceParticipants: int(row.SourceParticipants), Coverage: mapTFTCoverage(row.Coverage)})
	}
	return out, nil
}

// TftLineups is the resolver for the tftLineups field.
func (r *queryResolver) TftLineups(ctx context.Context, filter gqlgenerated.TFTLineupsFilter) (*gqlgenerated.TFTLineupsResult, error) {
	f := tft.Normalize(tft.Filter{Platform: filter.Platform, Patch: stringValue(filter.Patch), SetNumber: filter.SetNumber, Cohort: enumValue(filter.Cohort), Window: enumWindowValue(filter.Window), Locale: stringValue(filter.Locale), MinSamples: intValue(filter.MinSamples), Limit: intValue(filter.Limit)})
	if err := tft.Validate(f); err != nil {
		return nil, domainerr.Wrap("BAD_USER_INPUT", err.Error(), err)
	}
	result, err := r.TFT.Lineups(ctx, f)
	if err != nil {
		return nil, fmt.Errorf("TFT lineups: %w", err)
	}
	out := &gqlgenerated.TFTLineupsResult{Platform: result.Platform, Patch: result.Patch, SetNumber: result.SetNumber, QueueID: result.QueueID, Cohort: gqlgenerated.TFTCohort(result.Cohort), Window: gqlgenerated.TFTWindow(result.Window), Locale: result.Locale, AlgorithmVersion: result.AlgorithmVersion, PublishedAt: result.PublishedAt.UTC().Format(time.RFC3339), SourceMatches: int(result.SourceMatches), SourceParticipants: int(result.SourceParticipants), Coverage: mapTFTCoverage(result.Coverage), Items: make([]*gqlgenerated.TFTLineup, 0, len(result.Items))}
	for _, item := range result.Items {
		out.Items = append(out.Items, mapTFTLineup(item))
	}
	return out, nil
}

// TftMatchHistory is the resolver for the tftMatchHistory field.
func (r *queryResolver) TftMatchHistory(ctx context.Context, input gqlgenerated.TFTHistoryInput) (*gqlgenerated.TFTHistoryResult, error) {
	result, err := r.TFT.History(ctx, tft.HistoryFilter{Identity: tft.Identity{Platform: input.Platform, GameName: input.GameName, TagLine: input.TagLine}, QueueID: intValue(input.QueueID), First: intValue(input.First), After: stringValue(input.After), Locale: stringValue(input.Locale)})
	if err != nil {
		return nil, mapTFTError(err)
	}
	return mapTFTHistoryResult(result), nil
}

// TftLookupJob is the resolver for the tftLookupJob field.
func (r *queryResolver) TftLookupJob(ctx context.Context, id string) (*gqlgenerated.TFTLookupJob, error) {
	job, err := r.TFT.GetJob(ctx, id)
	if err != nil {
		return nil, mapTFTError(err)
	}
	return mapTFTLookupJob(job), nil
}
