ALTER TABLE runs DROP COLUMN IF EXISTS version;
ALTER TABLE runs DROP COLUMN IF EXISTS rank_prefetch_tiers;
ALTER TABLE runs DROP COLUMN IF EXISTS queue;
ALTER TABLE runs DROP COLUMN IF EXISTS execution;
