package resolver

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.91

import (
	"context"

	"github.com/crafff/gogg/apps/api/internal/transport/graphql/domainerr"
	gqlgenerated "github.com/crafff/gogg/apps/api/internal/transport/graphql/generated"
	"github.com/crafff/gogg/apps/api/internal/transport/middleware"
)

// Me is the resolver for the me field.
func (r *queryResolver) Me(ctx context.Context) (*gqlgenerated.CurrentUser, error) {
	if err := middleware.SessionErrorFromContext(ctx); err != nil {
		return nil, domainerr.Wrap("SERVICE_UNAVAILABLE", "session service is unavailable", err)
	}
	userID, ok := middleware.UserIDFromContext(ctx)
	if !ok {
		return nil, nil
	}
	account, err := r.Users.CurrentUser(ctx, userID)
	if err != nil {
		return nil, err
	}
	out := &gqlgenerated.CurrentUser{
		ID: account.ID.String(), DisplayName: account.DisplayName,
		Email: account.Email, AvatarURL: account.AvatarURL, Locale: account.Locale,
		Identities: make([]*gqlgenerated.OAuthIdentity, 0, len(account.Identities)),
	}
	for _, identity := range account.Identities {
		out.Identities = append(out.Identities, &gqlgenerated.OAuthIdentity{
			Provider: identity.Provider, Username: identity.Username,
		})
	}
	return out, nil
}

// AuthProviders is the resolver for the authProviders field.
func (r *queryResolver) AuthProviders(ctx context.Context) ([]*gqlgenerated.AuthProvider, error) {
	names := r.Users.Providers()
	out := make([]*gqlgenerated.AuthProvider, 0, len(names))
	for _, name := range names {
		out = append(out, &gqlgenerated.AuthProvider{ID: name})
	}
	return out, nil
}
