package resolver

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.91

import (
	"context"
	"fmt"

	"github.com/crafff/gogg/apps/api/internal/service/rankings"
	"github.com/crafff/gogg/apps/api/internal/transport/graphql/domainerr"
	gqlgenerated "github.com/crafff/gogg/apps/api/internal/transport/graphql/generated"
)

// ChampionRankings is the resolver for the championRankings field.
func (r *queryResolver) ChampionRankings(ctx context.Context, filter *gqlgenerated.ChampionRankingsFilter) (*gqlgenerated.RankingsResult, error) {
	f := filterFromInput(filter)
	if err := rankings.ValidateFilter(f); err != nil {
		return nil, domainerr.Wrap("BAD_USER_INPUT", err.Error(), err)
	}

	var (
		res rankings.Result
		err error
	)
	if f.Position != "" {
		res, err = r.Rankings.GetByPosition(ctx, f)
	} else {
		res, err = r.Rankings.GetOverall(ctx, f)
	}
	if err != nil {
		return nil, fmt.Errorf("champion rankings: %w", err)
	}

	items := make([]*gqlgenerated.ChampionRanking, 0, len(res.Items))
	for _, it := range res.Items {
		items = append(items, &gqlgenerated.ChampionRanking{
			ChampionID:   it.ChampionID,
			ChampionName: it.ChampionName,
			TeamPosition: it.TeamPosition,
			Games:        it.Games,
			Wins:         it.Wins,
			Losses:       it.Losses,
			WinRate:      it.WinRate,
			PickRate:     it.PickRate,
			BanRate:      it.BanRate,
			Kda:          it.KDA,
		})
	}

	out := &gqlgenerated.RankingsResult{
		Items:        items,
		TotalMatches: res.TotalMatches,
	}
	if res.ResolvedVersion != "" {
		v := res.ResolvedVersion
		out.ResolvedVersion = &v
	}
	return out, nil
}
