package resolver

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.91

import (
	"context"

	summonersvc "github.com/crafff/gogg/apps/api/internal/service/summoner"
	"github.com/crafff/gogg/apps/api/internal/transport/graphql/domainerr"
	gqlgenerated "github.com/crafff/gogg/apps/api/internal/transport/graphql/generated"
	"github.com/crafff/gogg/apps/api/internal/transport/middleware"
)

// RefreshSummoner is the resolver for the refreshSummoner field.
func (r *mutationResolver) RefreshSummoner(ctx context.Context, identity gqlgenerated.SummonerIdentityInput) (*gqlgenerated.SummonerRefreshResult, error) {
	if r.Summoners == nil {
		return nil, domainerr.New("SERVICE_UNAVAILABLE", "summoner refresh is unavailable")
	}
	result, err := r.Summoners.Refresh(ctx, mapIdentity(identity), middleware.ClientIPFromContext(ctx))
	if err != nil {
		return nil, mapSummonerError(err)
	}
	return &gqlgenerated.SummonerRefreshResult{Fresh: result.Fresh, Reused: result.Reused, Job: mapLookupJob(result.Job)}, nil
}

// Summoner is the resolver for the summoner field.
func (r *queryResolver) Summoner(ctx context.Context, identity gqlgenerated.SummonerIdentityInput, history *gqlgenerated.SummonerHistoryInput) (*gqlgenerated.SummonerResult, error) {
	if r.Summoners == nil {
		return nil, nil
	}
	page := summonersvc.PageRequest{Queue: summonersvc.QueueAll, First: summonersvc.DefaultPageSize}
	if history != nil {
		if history.Queue != nil {
			page.Queue = summonersvc.QueueFilter(history.Queue.String())
		}
		if history.First != nil {
			page.First = *history.First
		}
		if history.After != nil {
			page.After = *history.After
		}
	}
	result, err := r.Summoners.Get(ctx, mapIdentity(identity), page)
	if err != nil {
		return nil, mapSummonerError(err)
	}
	return mapSummonerResult(result), nil
}

// SummonerLookupJob is the resolver for the summonerLookupJob field.
func (r *queryResolver) SummonerLookupJob(ctx context.Context, id string) (*gqlgenerated.SummonerLookupJob, error) {
	if r.Summoners == nil {
		return nil, nil
	}
	job, err := r.Summoners.GetJob(ctx, id)
	if err != nil {
		return nil, mapSummonerError(err)
	}
	return mapLookupJob(job), nil
}

// Mutation returns gqlgenerated.MutationResolver implementation.
func (r *Resolver) Mutation() gqlgenerated.MutationResolver { return &mutationResolver{r} }

type mutationResolver struct{ *Resolver }
