riot:
    api_keys:
        KR: ENC[AES256_GCM,data:4erxjZ5PdE1fYH1CDZC2h+96n+YtOg8oB780eI9mnlmrzEBrVhBxHQBo,iv:beI6/1iic6hA6mSvn/cfJLh/TZR5NQM2ciegzu52Hiw=,tag:mGund8ia5vWfz8s/tldcmg==,type:str]
        NA1: ENC[AES256_GCM,data:CvTddX4aOmY5TbiIgpCxmxLI2bUEl8tyGH9Lnph/tqNrG5ZlCyax6uoY,iv:SX4z14BKUdMMM9At3t8Wir4FvaQy/2w8DtAqrrbzHGw=,tag:YHkbKacLbMv2JaRdPgvNDA==,type:str]
    jwt:
        access_signing_secret: ENC[AES256_GCM,data:PL9+2BXNsbksQYTu18ZBS7X5t0uKN/7auTvgPvSp+nS4e07zbzKylsiP05W+Xk5axnbbtJD8bC6SbnzHioh3kEA/mOwTpoty6Ddssc6uecbPOuGlaE1vqA==,iv:4ezJjoNHE1Mx5SeIV0LPb+8FfG+w0gfarmit6iEg9oo=,tag:dyXgaQ+x4l1uY9/IXVEV5g==,type:str]
        refresh_signing_secret: ENC[AES256_GCM,data:IM+UmWO/iMVCtPZBMmbTS5wbNx4YpG9TLj991nFgXxAjidR6daSJJSSpKkPdJeGd0RY/XPr2reHD8lLwRXcwzPcPUDUEfGTFByn/TpR/YFR9MptyxMOAiA==,iv:EuMuTGDc3Y45hNFMvp4LzlsL/3/Afrb0GWWI4KqTo2Y=,tag:/yW4DyHPkKiGfPHR6e/7NA==,type:str]
    database:
        dsn: ENC[AES256_GCM,data:B9nYBo4zND16quJ92s06cHEnJd0T08d2cWCuSFtjGIJXSlh4U7EuX/JtFissSEJ2m3n/4OlZnJ/ZWVKmIw==,iv:WyH4Y2aWkjbThDDKVwA8W54LpqTxozpvqBaK4ugN9Tc=,tag:2iiYGcJpGUuPcDz1YTVfBg==,type:str]
    redis:
        url: ENC[AES256_GCM,data:l8hlha53PhKEDGxUNFMs08pDH5GC6Rst,iv:ZxiAuC2UywxIYa7Amajyf6Te1U/Xl5NfhSfuRJODgqE=,tag:wEKPDkX/TRKYtB8xteJu5w==,type:str]
    oauth:
        discord:
            client_id: ""
            client_secret: ""
    google:
        client_id: ""
        client_secret: ""
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1uu94t94nwza8jen4prn428m6p42qx2tn5fl805xagsfl2a07z97s8zcezw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRdUpzRGlndmNRYzVOeWlF
            QmN0Y1NoS29JbXg4MkNoQk1XR2FaaXEwWEF3ClR1UVdxY2hwZ1RTVVFlblNjeEFD
            RVFMQ1IwOGJ4a3JDRmxSOFIzZEorbXMKLS0tICtWVWZDK1RxLzZ4dHFvZVRRNWph
            dm9VMmVTRjYyblpOSEs4WjZaZkNZQTgKTgE+Z4JFSeYKkPGLuXYvOuNatByU4x/R
            ZX203O0IXhC3UNrPIN0G0IfwvOLAhiv09n1hGNXw28ScR7Rs8AqR8g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-13T03:48:30Z"
    mac: ENC[AES256_GCM,data:RqFi8fG4s5GSTMMP5pGLCiM8xGbcRIzN5EbBZ0BL3xcILE2zwtUphQt8W22GMoLQnc5z5ucp6RKYUMSK3RZFEG3VAkI1EzS2pjf5dn5mW1ZRNWSskKPE8OOV8Cbvso+j4Tg37z++Vfd4KLU4uAEoucnb/hHqmLGWvpVh2F7jO/w=,iv:4ZELz4GBR2tlqrIER2vrjXoGzrJwUa2F8GCH7/gJWvw=,tag:QLgdDP3AeHFg3BVPnCunLg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.0
