api:
    port: ENC[AES256_GCM,data:2f3LKg==,iv:Mi5IagIEGyvUP5FrhlObGjHz0RiEv71IF/CIOhJORfc=,tag:hMx4SybeXyzJmOgQtkPWnA==,type:int]
    read_timeout: ENC[AES256_GCM,data:XeOf,iv:nuJ6pMUPLa3htZR/7pfjjFmqBAf7OS3P9xUOkufsYtQ=,tag:tibk+ODkGO/HkwEmFJlzpg==,type:str]
    write_timeout: ENC[AES256_GCM,data:n3G8,iv:A43RtjRmX+qodq0bwLNHWcu93psq4WrSe2LdE+2KMpE=,tag:/isZcAGIPSNXkNJpVFUgoA==,type:str]
    idle_timeout: ENC[AES256_GCM,data:mEQr,iv:qDlnoBnYPuB5TzA9YUmnzuGvV9hxinauq2RLr1W2keM=,tag:WLSHP3R/BGmuV+Z7XIwr2A==,type:str]
    shutdown_grace: ENC[AES256_GCM,data:wKDn,iv:98Hgm2XtN6YA0efLdBOHTmkkrMloqTITmmXwLugiXrE=,tag:/OLVtyHvx6SNAMS+1pkuJQ==,type:str]
    allowed_origins:
        - ENC[AES256_GCM,data:LX4BhpmaSXkRE6e+opbRscK8jMF/,iv:d9anRwNNDWVdj4pt4oSjOQkaoWyW9asv0xK+cB45Xgw=,tag:k6Ijp0SiQ0VG3jAITI9e4A==,type:str]
        - ENC[AES256_GCM,data:pm5TjmxNg1mLOfYadQWrUZ/LdbaI,iv:zxph9y4axgypPWaXPeWaIAB1iw4BFK9UgjvwmJIdTt0=,tag:/6HMyFUH2z7uFOqj/MPbxA==,type:str]
    graphql_playground: ENC[AES256_GCM,data:p0rMxA==,iv:cYb9ZdOOncj0i3I34DeBxMWAQwwhyfYokGId2tzFykg=,tag:UCmiEYoo8ukfZUw2MU0Lkg==,type:bool]
temporal:
    host_port: ENC[AES256_GCM,data:0CYLJ07rLOi+NYJuVuM=,iv:nfQHJYApEWIqf4B3usei+CP36BrcITDX7GhWhri2CVk=,tag:DVHv5hbaNIXhlJyFNdk9Hw==,type:str]
    namespace: ENC[AES256_GCM,data:JJP9M97sEw==,iv:FKd3GpfnEjrdJ5Ft6WCQfBAqfnN92hXT7ki8kuB8bqs=,tag:3cbqa/LAH8v5vPj3TNCRSg==,type:str]
    task_queues:
        - ENC[AES256_GCM,data:JDnOJpSErUk=,iv:0aOa41jwC5aEfCLUAm4uuLcv6G7BOrIi3hTVG/Rf1/Y=,tag:HZzGaqvKyhmx9k105UaoBQ==,type:str]
        - ENC[AES256_GCM,data:jwbhWkhem8Md,iv:LuqiOQ/ofe7eppM7IRo7o718QchJAFCFLjP0mnOfGGk=,tag:ChZO+kZs1heQt8EzPmGBJg==,type:str]
database:
    dsn: ENC[AES256_GCM,data:9pgAwAFenZninv9AHSA1lvZRRYsjmhno3LDgU04VzigFe5kwoD1DlHzEzlzpB39at0XnHWJ0al+72oUgbA==,iv:x+IPMsv9SGuK16vJ/L168jqfmzruuZFtgy1Jx5ib694=,tag:BcFU8ojoh+tWMwqwJ85l2w==,type:str]
    max_open_conns: ENC[AES256_GCM,data:F3Q=,iv:A5ZdANvyQNnx8BtkYjjuv2NBtn0eN4V2TVYU7mSKq4c=,tag:EgsLBPcJl9lioXjhDIkXIg==,type:int]
    min_idle_conns: ENC[AES256_GCM,data:Tg==,iv:eCwWp3KV4a/otiXxfRIO4GEt132e0cNbNiLPgG2Fg6U=,tag:ywlmjm+284hiUtUugecMWw==,type:int]
    max_idle_conns: ENC[AES256_GCM,data:kA==,iv:5fM55Cwi12R1JgXr0FMcQmS0q11UTGtFiY+yYVNCOUY=,tag:tOhFEWBQ4lXhTv9bhDycEQ==,type:int]
    conn_max_lifetime: ENC[AES256_GCM,data:wsM=,iv:nL3qBHFefb4EX/z/emNtZaqDLDzXP3uEfUybIQ52mWg=,tag:WHaqkxG+5LaPmBUQdeSuMg==,type:str]
    conn_max_lifetime_seconds: ENC[AES256_GCM,data:gFB1,iv:DoARo3aPG4gbL7wsc9AmlmkWwr2NvUM5m8rI9eZTcNE=,tag:JSmGMEX28FoJOQzEVK5HCA==,type:int]
redis:
    url: ENC[AES256_GCM,data:+XT8kM4Spltxvw4h1vOxn73gip9m4nC0,iv:Dva92Vhyl4xpHCuImSEVrPqFc6qbYTisWyFetjaUtBQ=,tag:D3nZ0N1fmXMU/HKdmRIBvg==,type:str]
logging:
    level: ENC[AES256_GCM,data:mNZaLQ==,iv:tx61FxsewpxpecMO3mQq1+LMXu2nUheTTf+39nEe9XE=,tag:kK8bziVi60QEMr7Ei/mujw==,type:str]
    format: ENC[AES256_GCM,data:Xp9rIg==,iv:VvX0RWK7dqKBtzcoKuzjSfB7Kvgf2VaezF4BCaV9gT0=,tag:mXP04+hk31NF6vHbmvxHkg==,type:str]
auth:
    jwt_secret: ENC[AES256_GCM,data:C0Hl3p8qxwM6crek7qdaM+oiVZ8vsw1CAJit/4in+TGS5D94KePNONJ48KJ4L/W1H9tkFeCYdYt0HTvBkKT6YS62vp1ry78ZwC/8nPvWVnuZ1DbrXGNZAA==,iv:/7itdmayxZf212cObfIV18pXWjdZeM/w/LTilWctgLk=,tag:5UuquNhwVWKwMFaRaBX6Vg==,type:str]
    issuer: ENC[AES256_GCM,data:X7j0qWXuFGcAJA==,iv:IAjVKRkA0ZgZ/5CQoK580B3YHbQty2AfKJQ//FTzb3s=,tag:Cb6wrC/7hyn6z80bbsiT4A==,type:str]
    access_ttl: ENC[AES256_GCM,data:4SHZ,iv:AFeRvQRcmQHjrrRKrkZ84IbWWq4PAsKGQ/AVpaWj57s=,tag:cq9YBc+Ce2LYHV1L4JlXyw==,type:str]
    refresh_ttl: ENC[AES256_GCM,data:Am/+5A==,iv:zbrsSVZNkNXHoJu25UqGeSzyvhnVDWUI7k0nZyGCibw=,tag:K9QK1r2mB8NOVY9b773Buw==,type:str]
    cookie_domain: ""
    cookie_secure: ENC[AES256_GCM,data:lwnUYzw=,iv:71YomI2t+saG8p2aGd3371OR2Qvka+QX1VEhl29NoB4=,tag:FbVJQFFn7JFKqLK0L7vQ1A==,type:bool]
oauth:
    discord:
        client_id: ""
        client_secret: ""
    google:
        client_id: ""
        client_secret: ""
        redirect_url: ""
riot:
    api_key: ENC[AES256_GCM,data:/8eej7Coo3V8b8ke05egfyENzcfmUGrl44uLCW0AV5hA/lhvmWqs6fhy,iv:DGzoWbXXA6lkr2IG/IxwB78j2IQqRhCGk/xs1/i1Ga4=,tag:iL06hIwYNLg1Ki2F4nv79w==,type:str]
    base_url: ENC[AES256_GCM,data:ha1SEh2pQq+19aVi1maC2K6HiktHUsYokuEidg==,iv:AhIgkcOP6Fi0A83L2SdOCFG+xwHOEaEoCHgNQiWBhek=,tag:BeuJgpKVqjaLRXc1lF2Hug==,type:str]
regions:
    - name: ENC[AES256_GCM,data:sIs=,iv:fbFn72RgKJZlVb+AZZo7ya2Utnu6TwyXrzu+eB1r5do=,tag:H+3GIPjnm/OGqRYDGOAXLw==,type:str]
      api_key: null
      base_url: ENC[AES256_GCM,data:slFhzl9radvRQ3zBzvHHYgDgJU7zVwHvKd76lw==,iv:XLAIm+fooMOeCXWHGAsm+moooBXJlZGRVW/rUuFMBk0=,tag:vynJ+vlQcKVcu/ZYGFIQPQ==,type:str]
    - name: ENC[AES256_GCM,data:m6WM,iv:kwkKoBq4tNKd784exvKNY8VbTBEpE29vVEdLRdZKSXs=,tag:cOpduj0OL9nsoDehjuPm/Q==,type:str]
      api_key: null
      base_url: ENC[AES256_GCM,data:8AIlwVl2ggHZUxi5y2zVPBZyJfC2xcWrXyVnN9A=,iv:SDCw1OkRV5NYIxyV4LjCWbFhCB6FrXnbn0rh5XxdegM=,tag:C680cqa3xT0OmrsG2cTPJg==,type:str]
run_profiles:
    daily_kr:
        region: ENC[AES256_GCM,data:8tI=,iv:hbVB03rzJEEWdsK1zwQDvJUaMOlQUn6MjJbdOsfwj4s=,tag:G09R5BLajBiBemAReEFDjQ==,type:str]
        mode: ENC[AES256_GCM,data:EggkL8hccVE+50I=,iv:XkiV7Qp/18itkO6Bfn/QHJjKNS7qa1bKnf5af3Y/u9E=,tag:9zgyvhUxt4ORwHLax7Ra7w==,type:str]
        target_tiers:
            - ENC[AES256_GCM,data:qSphPJjQ+ZxBcA==,iv:MBdp26xwIbiapJL/31sbYvFwrh4CrXOZU9eLX1do4sw=,tag:YVhNB9acxQhcHEOdvEv4kg==,type:str]
            - ENC[AES256_GCM,data:sBFhwcaWS39qxJc=,iv:xh3PjBJbMstjCM8kvFWRzOrTBcqwJk7uPOXKlBtovTc=,tag:0sxl0h136U4aQhJ1+jhVDw==,type:str]
            - ENC[AES256_GCM,data:OD+ssVm5,iv:S/OfDsdHwO8mxdyBSF15h+LsAbhkBM8auErIy4q/3KA=,tag:HqLu6L8/PZ5YKiOGNoFo5w==,type:str]
        rank_prefetch_tiers:
            - ENC[AES256_GCM,data:DiRCLQG73dTUHg==,iv:SMMkwh+UCU02+eskfXDGSHU3/uSZ5wa3Gx9fpom4J0o=,tag:qUuIOSwmiPSZ2jXTwda4ag==,type:str]
            - ENC[AES256_GCM,data:mTfy7D8mnFqC8lk=,iv:q0vCgpQ+MI5TK4PyctjdCknVred33p2s15o9dhXNI0o=,tag:0eHtJWbVqQYOwb8XrDzRkA==,type:str]
            - ENC[AES256_GCM,data:QwOgv7qZ,iv:ocn9iG+gTMWO3kpkfuuAts4cxYqy5LVifpxxC1+6PCw=,tag:rtCSqg/9et4HPRWwvhquig==,type:str]
            - ENC[AES256_GCM,data:o2e2wrcblA==,iv:Ik9b+a947UWG+Bg1E4+fUtc8GYKwGTKVk0GCVZj7Seo=,tag:MhPnShj/wKiVQAlq7j6PpQ==,type:str]
            - ENC[AES256_GCM,data:yP3O5wTAZw==,iv:8au1v+PYR9cAe0ebmbQX0q5wejPS6GopFp3zRn1aC68=,tag:cjE6jv486RtCMZWLLKY4xg==,type:str]
        queue: ENC[AES256_GCM,data:GHaKapBZZw0qaNVLy7s/,iv:cRIa1ggrPIP3zYS5Y9tx5k7PZ/CzC0iIDlDvomJUz/A=,tag:4lTLnninvJQsk9G/AJtl5A==,type:str]
        execution: ENC[AES256_GCM,data:c55TcZ/nImk=,iv:VeSFQ4lAdpvGo0ghB1L6qtFBP9DbCRr37Uogxx/JlyA=,tag:Z2bqpzBovn1YKK1exENHpA==,type:str]
    daily_na:
        region: ENC[AES256_GCM,data:6Z6n,iv:XHR3j158TzVj70MMic1MBpARGWXzEpcw33wMBRUgX3g=,tag:ROo1iXfQDlyjqF3+i2oV1A==,type:str]
        mode: ENC[AES256_GCM,data:EG2/UBK3Z5EyNug=,iv:DWQw/MdvtIpo/OE6G7cA9ry/Vpyk4EJrpRFT2akwD18=,tag:CA+/BNOjUpZcW0pEtbNEdQ==,type:str]
        target_tiers:
            - ENC[AES256_GCM,data:IC09GMukrjjOmQ==,iv:p3wkj6p3nyA5S9ZFAzRRFQv/AWsqui0IjQkFIkER93U=,tag:eWvfqJ8qZE95wJn5WhxybA==,type:str]
            - ENC[AES256_GCM,data:sNtP+7GNuTTGDBg=,iv:UWoXhiwryt8FWZIR+qaWFC8cwkEK2ngLKuCVZIrJZhA=,tag:FjuXBu12SJtqijnX9iyM5g==,type:str]
            - ENC[AES256_GCM,data:lhc4eEeB,iv:70MMPSwOG0C5MkLVaV9zx09V1HSXKnlqZ++cYZPhnSg=,tag:fV3+jxU7d1PEK5cDzf+iYg==,type:str]
        rank_prefetch_tiers:
            - ENC[AES256_GCM,data:ZdFhUe28AsgqIQ==,iv:UAKhtsukE1wPUnSGlfOsP4E24tlJN4otQpvbpujo9I8=,tag:4mMYicO52XxdXAigeeUp6g==,type:str]
            - ENC[AES256_GCM,data:3QfVGuqPYsPJng4=,iv:DvT51lFZ/kjZOS11jZAzggDQAg9jtcZdE2GdIGv/oqY=,tag:679T40DZNnI1t69O+cG+Yg==,type:str]
            - ENC[AES256_GCM,data:c+Zi9+DC,iv:4jofnXkS8hF4hcvbR6bE1V/kdtFZRp/QVsJXaW+ZKsc=,tag:AFFvHvoYNi4IdzXe+5GLkQ==,type:str]
            - ENC[AES256_GCM,data:mQL1Bwu+Ow==,iv:1PjYSMF5m73EBQfAwWwVAn9vDnc47kWylvnLq/frC/w=,tag:KwuEkJKxGMQe/Ff53kD1tg==,type:str]
            - ENC[AES256_GCM,data:ZIkeCgxEDA==,iv:iLdemZkZ33JW4aUqYlNCZ8Bm1YHZ5uC/nq5OXvTOTsE=,tag:qhyBI1e3MKmbyM7tEJPG7A==,type:str]
        queue: ENC[AES256_GCM,data:GlBOdJXvjH5sp04p63os,iv:p9xaExyYVS0/NosoAp2oxxmQDKHkiOadpifeNKlduy0=,tag:HocbLasIiV+Dce+O4G8m5g==,type:str]
        execution: ENC[AES256_GCM,data:HbYhMJ0IcOY=,iv:XcSMBJExay1aGt+jAGhLTXKEGlhyWEUDriQBL1Jo2/c=,tag:7stWXMWYzrOjdm6taWtOMg==,type:str]
    historical_kr_16_13:
        region: ENC[AES256_GCM,data:CA0=,iv:aOnvXA7lrlVCo0koy53hmvWH3sOeyGhFdLih5Yi+19Y=,tag:cNbN4OoQGrxbXWVnXT3dwA==,type:str]
        mode: ENC[AES256_GCM,data:R7Jl+zUN0JMlAg==,iv:qmt85EIVt8ybBFzh6rwkR/PAMOV+sHvwdmnS+/X4Tw8=,tag:m1GrW8sIFz/tUJnZyKzZ7A==,type:str]
        version: ENC[AES256_GCM,data:UQRrrLM=,iv:e4AgTah0gadsRI7nbL9Irp/08OOoxQUKhbmR3y78sJE=,tag:G0KXp3QzSncJ6/nJYileEg==,type:str]
        target_tiers:
            - ENC[AES256_GCM,data:+oHwk7HkUESBEw==,iv:Y0Kf7hxG9D5PuHNB/lJDJmLK+PC4B1JOl8qCxWfXKSY=,tag:ZXEUGNd8s/a5x3uSIlfigg==,type:str]
            - ENC[AES256_GCM,data:UtmtG4Sl7A2960Q=,iv:1KxXPTuai5QgZTcq8kRywJlV37tOlDbUZhbf7EhW2OA=,tag:hjo7b/XvxJrssTQ5y/M/mg==,type:str]
            - ENC[AES256_GCM,data:6UCAQ/qJ,iv:t/odT2pLvsvDu0kMQIyslUnEORLWJ0Ew4CIRL4PUQt8=,tag:i6OaY7XS3RqaL+3QGQHe6Q==,type:str]
        rank_prefetch_tiers:
            - ENC[AES256_GCM,data:mwZDWXnRPom7FQ==,iv:M4SatSVvxSfXWCQr46nODmEiMTJLYmmxFam5b0mxhks=,tag:7rys+Jho67+VW2o8SjubeQ==,type:str]
            - ENC[AES256_GCM,data:avN4SSdadQvlf2c=,iv:xaV+UldgHblTH0kqviKhOIZVhv+kqGsmRXA1wniCcNY=,tag:utgIAXVOBvyFnbhdxxPGIQ==,type:str]
            - ENC[AES256_GCM,data:lJ2+e65q,iv:FfrSHNdAY0WPub+VJ+JWZXcoaIEsTQ9Ra8EYYCVf098=,tag:3Wv86GXohPWMhIiASNH1RQ==,type:str]
            - ENC[AES256_GCM,data:QzCeNhwtaA==,iv:P4WKxH+PkfP2gwdMlHNl/HdfwvIKFW2v2EQ1FvcNuD8=,tag:1JFNs548n4ndkWNAIaOBuA==,type:str]
        queue: ENC[AES256_GCM,data:M6uLCe9zahEI8QBfi7t4,iv:ETnie1TWyhb/j2zjjvU+K5cp9ttcW1nKWSKGpw5iK6s=,tag:NK7Ry0+8alHX+liWdoOhkQ==,type:str]
        execution: ENC[AES256_GCM,data:a7oUq929bcI=,iv:Bo85uYSep+xBsb1GalfQT3FM1nZJ4Ql2SjZ5lPQCaFQ=,tag:I4OxSNPkjfnegnSu/0LFvw==,type:str]
    historical_na_16_13:
        region: ENC[AES256_GCM,data:Yxs8,iv:qudU6XZgU7rKcsH4DKnOucmi20WwWB1DuJ4PVw8+D28=,tag:AhHafKFOCzTbhIAkFBtcEw==,type:str]
        mode: ENC[AES256_GCM,data:WKKud3Z694k7OQ==,iv:wBcF4XDnPrZ9wrPR1AImobkVuaQEH3IE09OnvRM2aJ4=,tag:Jak4wk8RP8N7UIhhhpXtKA==,type:str]
        version: ENC[AES256_GCM,data:ZNEkWDk=,iv:/2dXHTQFNpXp9ZkJIBG87HCiAEnWhmCuGBuAtvy0ndQ=,tag:giXSvje7CnvCUbzi3rjQWQ==,type:str]
        target_tiers:
            - ENC[AES256_GCM,data:30LALVggigArlQ==,iv:BUQzTFmaBtZr2sF9nGaXFaSGCLQUQvr6Yt0HONl1UHA=,tag:OZU5vse3fAjQljWBw75yEw==,type:str]
            - ENC[AES256_GCM,data:Z0WiHGZIdt58zkE=,iv:BarzIdlxzJcsa4QQ7K+6G71NaJeFAYwRaItPfHNLj0Q=,tag:ZRiTS15mFYl2WCGIt+oAxA==,type:str]
            - ENC[AES256_GCM,data:BIejXhKX,iv:xIgqemi0gS2/VCSaeH8mwAH2zwgc/DsmUYHMAYIabK0=,tag:t0GKOUb4aE/UNBZilsBUnQ==,type:str]
        rank_prefetch_tiers:
            - ENC[AES256_GCM,data:R8oNDBpb0By8og==,iv:cYvzlrlrKhVDk2y2S9l0nFaVKcyx3+kIJQT3NkoWciI=,tag:wciR41eYQMhTiT6vBgpn4g==,type:str]
            - ENC[AES256_GCM,data:p/nUKqma4FkLrlI=,iv:bLzU4qAi3LzP0SNT+n54N7UXYcvdt3dGf9zz0KAyKqg=,tag:TF0bFk1mt0766Hbs4SnNLA==,type:str]
            - ENC[AES256_GCM,data:rj0YwfPJ,iv:08DiX1RLDca54ilYmwmpjJRtNuCK2kgfdip3MVKtM2s=,tag:bb7FXb69enrCNIhScMMhtA==,type:str]
            - ENC[AES256_GCM,data:sQaQsXbnsg==,iv:qPKpFPVlDP8eQDPLWnQgKNbZeaCEDdjMBBCo5I0lcmc=,tag:iKo4schP0jh5bhrPXM7MWA==,type:str]
        queue: ENC[AES256_GCM,data:f3gnkvnR7xQQWF66JsGE,iv:ESNgxbW5Jh9PN0uShFcPdSGCAA+rh5b/vFfdCwhpgTQ=,tag:UBRtltvXVehAVZXkD2GdqQ==,type:str]
        execution: ENC[AES256_GCM,data:6ke3v0gFcds=,iv:DhCU6D9wTT6T3KkS+2NT2/I3SNOgK/kprrlo2xJH0sA=,tag:+b9uLvXd7dAC/QlIaew9og==,type:str]
#ENC[AES256_GCM,data:NIHzjfPucad5QA==,iv:ZqaNG/vtAcEjDjqA6D4n8FjFEiUzqQNPlbi1wVHowKU=,tag:lyKxwQvcXKBehZzydz+gsg==,type:comment]
#ENC[AES256_GCM,data:Ytw4qOXliF2T4frvBw0q2q0hzfsE2w==,iv:ZbHq09MBMEtJ+VZWtgpTPgygT5q28S4fr0KHlDRS82w=,tag:NYIEv6hFfazY6kBS/LWf5A==,type:comment]
#ENC[AES256_GCM,data:Rgn+Mnq1P7TfFcdW9uzZFBOv0kjT/9U8,iv:Hh//IAVL49ag0JSTaitbcuaVJ+atJcqwv8uEpDm5Z6c=,tag:C06Gv9u3bQ5y7fusjtVFFg==,type:comment]
#ENC[AES256_GCM,data:Ytw4qOXliF2T4frvBw0q2q0hzfsE2w==,iv:ZbHq09MBMEtJ+VZWtgpTPgygT5q28S4fr0KHlDRS82w=,tag:NYIEv6hFfazY6kBS/LWf5A==,type:comment]
#ENC[AES256_GCM,data:ntQWS98dGbSjcLlylAQTcWlb6iswcAgc,iv:HQ06nngmr44YRgU0pnWNCdLPG7H6KGIdzPMLF19QOko=,tag:sa6jiXKxQmtYHltkFGdsoQ==,type:comment]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1uu94t94nwza8jen4prn428m6p42qx2tn5fl805xagsfl2a07z97s8zcezw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaU1daQ0U4cmhZNldiRXNr
            Zm90VEdrZUp0Z2xuSFhIakgydGlxR3lNZG5VClB3a1dYODVQQnl1YVlKa2g1ZFZD
            cGR4d1llNmlORys1b0drMjJ6Zk5pZG8KLS0tIFE2US9Lc042bVVGQ3Jaa0FKTlZl
            SFAzWGlCZ2FWdFRGazVhM0QvYXV6WmcKUM2IYZNSjMLe231h+0rmNQSxhVIvAmhz
            toIGG59j7RJHiGZ6DvT3nj2496LhgfHqYB49HEbd+osMWcrIyPypuQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-20T04:23:20Z"
    mac: ENC[AES256_GCM,data:Ya3PXeoRAiifdvzuQZnwXs1xB64p3pfqywIjCi7cmmdtdKAJgtSXUOYlpvHI07qxD3uPaMN7tHy+iYZjOTLieTbbEtn43KVCI2GRxDK3KEzxEE1TJ+QE7AHbzGW+krsko9loky3ujAkseZ8M20ItFCl6VEZuLz3koBT0yVqnf+M=,iv:njy41ycYO7KAeHKxudSapbjj9cZabMvRrJEIDL3vSu8=,tag:fPVd+Hqi5hO2ycJ12njkvQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.0
